name: Bug report / Bug 反馈
description: Report a bug to us / 反馈一个 Bug
title: "[Bug] "
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: 使用的版本 / Version
      description: |
        你使用的版本 (版本号 或 commit id) <br/>
        查看 commit id: 执行命令 `git rev-parse HEAD` <br/>
        *The version you are using (version number or commit id).* <br/>
        *Check commit id: Run the command `git rev-parse HEAD`*
      placeholder: "e.g., 1.0.0 or abcdef1"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 描述 Bug 情况 / Describe the bug
      description: |
        此 Bug 的表现或影响 <br/>
        *The manifestation or impact of the bug.*
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 如何复现 / How to reproduce
      description: |
        复现此 Bug 的步骤 <br/>
        *Steps to reproduce this bug.*
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 预期情况 / Expected behavior
      description: |
        清晰，简洁地描述预期情况下应该发生什么 <br/>
        *A clear and concise description of what you expected to happen.*
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 截屏或日志 / Screenshots or logs
      description: |
        如果可以，添加截图或服务器日志来帮助解决问题 **(注意删除日志中的 secret)** <br/>
        *If applicable, add screenshots or server logs to help explain your problem. **(remove secret in logs)***
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 其他内容 / Additional context
      description: |
        其他关于此问题的信息 <br/>
        *Any other context about the problem here.*
    validations:
      required: false
  - type: checkboxes
    id: confirm
    attributes:
      label: 提交前请确认 / Please confirm before submitting
      options:
        - label: 我确认现有的 Issues 列表中没有与这个重复的问题 / I confirm there is no duplicate.
          required: true
        - label: 我确认已经删除日志中的敏感信息 (如 secret) / I confirm there is no secret in logs.
          required: true
        - label: 我确认检查了上面的事项，并创建此 Issue / I confirm to commit this issue.
          required: true
        - label: 我未认真查看上面所有内容，只是一味勾选所有复选框 / Don't check me.
          required: false
